<a href="https://colab.research.google.com/github/Parvez-kamaly/NUMPY/blob/main/NumPy_Introduction().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating NumPy Arrays

In [ ]:
import numpy as np

In [ ]:
#create 1D array
x=np.array([1,2,3])
#create 2D array
y=np.array([[1,2],[2,3]])
#create 3D array
z=np.array([[1,2],[2,3],[4,5]])

print('1D ARRAY:-',x)

print('2D ARRAY:-',y)

print('3D ARRAY:- ',z)

1D ARRAY:- [1 2 3]
2D ARRAY:- [[1 2]
 [2 3]]
3D ARRAY:-  [[1 2]
 [2 3]
 [4 5]]


In [ ]:
a1_zeros=np.zeros((3,3))
print(a1_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a1_ones=np.ones((4,3))
print(a1_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a3_range=np.arange(0,10,2)
print(a3_range)

[0 2 4 6 8]


**NumPy Array Indexing**

In [ ]:
#create 1D array
arr1=np.array([1,2,3,4,5])
#single element access
print(arr1[0])

1


In [ ]:
print(arr1[-1])
print(arr1[2])

5
3


In [ ]:
#create a 2D array
arr2=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(arr2)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(arr2[1,0])
print(arr2[0,0])

3
1


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
#elements from index 1 to 3
print('Range of elements:',arr[1:2])

Range of elements: [[4 5 6]]


In [ ]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90],
                [100,110,120]])
print(arr[1:4])

[[ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [ ]:
#all rows , second column
arr[:,1]

array([ 20,  50,  80, 110])

In [ ]:
arr[1,:]

array([40, 50, 60])

**NumPy Basic Operations**

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])

#addition
add=x+y
print('addition',add)

#substraction
sub=x-y
print('substraction',sub)

#multiplication
multi=x*y
print('multiplication',multi)

#division
div=x/y
print('Division',div)


addition [5 7 9]
substraction [-3 -3 -3]
multiplication [ 4 10 18]
Division [0.25 0.4  0.5 ]


In [ ]:
res=np.add(x,y)
print(res)


[5 7 9]


In [ ]:
res=np.subtract(x,y)
print(res)

[-3 -3 -3]


In [ ]:
res=np.multiply(x,y)
print(res)

[ 4 10 18]


In [ ]:
res=np.divide(x,y)
print(res)

[0.25 0.4  0.5 ]
